### ISSUE TITLE
Replace difference of 1 with digits of pi

### ISSUE THREAD

**Issue by printfn** [pipct/propreantepenultimate-card#24]

**Comment by johnguant** [comment]
:+1:

**Comment by printfn** [comment]
0 would be a 10, 1 an Ace

**Comment by NickGeek** [comment]
No

**Comment by JJJollyjim** [comment]
@NickGeek please elaborate. That is not exactly constructive…

However, I don't really understand this rule. Does this mean you can match any substring, or have to start at the start? Obviously any substring means that any same-suit chain is valid…

This could be refined to add a fun aspect of skill and memorisation to the game, though maybe a different irrational number that Toby doesn't have a big head start on could be better.

**Comment by printfn** [comment]
We were discussing some stuff at lunch, and this was never more than a random idea.
The idea was to either allow or disallow any subchains of the first 50 or 20 digits of pi.
