### ISSUE TITLE
Attacks should require matches

### ISSUE THREAD

**Issue by printfn** [pipct/propreantepenultimate-card#26]

**Comment by NickGeek** [comment]
What do you mean by this?

**Comment by printfn** [comment]
Rename §4.3.1.2 to §4.3.1.3.
Add §4.3.1.2: it must be a type 1 match,

**Comment by printfn** [comment]
Basically, 2s and 5s must match suit.

**Comment by NickGeek** [comment]
I like +1

**Comment by printfn** [comment]
I think this is much less necessary after #30.

**Comment by NickGeek** [comment]
@printfn Agreed

**Comment by JJJollyjim** [comment]
I agree that this should be closed having merged #30

**Comment by printfn** [comment]
Ok, closing now.

**Comment by NickGeek** [comment]
One more confirm needed to close

**Comment by NickGeek** [comment]
Chris, Rhys or Logan?

**Comment by johnguant** [comment]
:+1:

**Comment by NickGeek** [comment]
@johnguant is that in favour of closing?
