### ISSUE TITLE
Make chains a bit harder

### ISSUE THREAD

**Issue by printfn** [pipct/propreantepenultimate-card#30]
Whenever a card with a numeric rank is played, its rank plus the sum of ranks of cards with numeric ranks of the topmost and penultimate cards must be divisible by three.

**Comment by NickGeek** [comment]
This might make creating chains to hard to do in a timely fashion.

**Comment by printfn** [comment]
Would summing really be that difficult? What about only the last two cards?

**Comment by printfn** [comment]
Updated issue text.

**Comment by JJJollyjim** [comment]
This was agreed upon at lunchtime today.
